quarkus.web-bundler.dependencies.auto-import=all
#quarkus.log.category."io.quarkiverse.roq.frontmatter.deployment".level=DEBUG
#quarkus.log.category."io.quarkiverse.roq.generator".level=DEBUG
quarkus.default-locale=en
quarkus.asciidoc.attributes.icons=font
quarkus.asciidoc.attributes.source-highlighter=highlight.js
site.slugify-files=false
site.collections.marketplace=true
site.collections.marketplace.future=true
quarkus.qute.web.markdown.plugin.alerts.custom-types.INFO=Information
quarkus.qute.web.markdown.plugin.alerts.custom-types.BUG=Known Bug
quarkus.qute.web.markdown.plugin.alerts.custom-types.SECURITY=Security Notice
%dev.site.draft=true
%dev.site.future=true
