name: "Build and Deploy Roq Site"
description: "Sets up JDK, builds the Quarkus site, and upload the GitHub Pages artifact."
inputs:
  setup-java:
    description: "Whether to setup Java or not"
    required: false
    default: 'true'
  java-version:
    description: "Java version to use for the build"
    required: false
    default: "21"
  java-distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"
  maven-executable:
    description: 'Choose whether to use mvn or ./mvnw'
    required: false
    default: './mvnw'
  maven-cache:
    description: "Maven cache strategy"
    required: false
    default: "maven"
  site-directory:
    description: "The directory containing the Roq site"
    required: false
    default: "./"
  maven-build-args:
    description: "Additional Maven build arguments"
    required: false
    default: "-DskipTests"
  github-pages:
    description: "Whether to configure and Upload GitHub Pages artifact or not"
    default: 'true'
    required: false
  github-token:
    description: "GitHub token for accessing GitHub Pages url (required if github-pages)"
    required: false
  site-url:
    description: "The full URL of the site including the eventual root path (required if not github-pages)"
    required: false
  artifact-path:
    description: "Path of the artifact to upload (from the site-directory)"
    required: false
    default: "target/roq"

runs:
  using: "composite"
  steps:
    # Step 1: Set up Java
    - name: Set up Java
      if: ${{ inputs.setup-java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: ${{ inputs.maven-cache }}

    # Step 2: Get GitHub Pages URL (if not provided as input)
    - name: Get GitHub Pages URL
      shell: bash
      if: ${{ inputs.github-pages == 'true' && inputs.site-url == null }}
      id: get_url
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
        echo "SITE_FULL_URL=$url" >> $GITHUB_ENV

    # Step 3: Setting environments for the build
    - name: Setting envs
      shell: bash
      run: |
        url=${{ inputs.site-url || env.SITE_FULL_URL }}
        if [ -z "$url" ]; then
          echo "site-url is required if github-pages=false"
          exit 1
        fi
        path=$(echo "$url" | sed -E 's|https?://[^/]+(/.*)?|\1|')
        url=$(echo "$url" | sed -E 's|(https?://[^/]+).*|\1|')
        if [ -z "$path" ]; then
          path="/"
        fi
        SITE_DIR=${{ inputs.site-directory }}
        SITE_DIR=${SITE_DIR%/}/
        echo "SITE_DIR=$SITE_DIR" >> $GITHUB_ENV
        echo "SITE_URL=$url" >> $GITHUB_ENV
        echo "SITE_PATH=$path" >> $GITHUB_ENV
        echo "Using SITE_DIR=$SITE_DIR, SITE_URL=$SITE_URL, SITE_PATH=$SITE_PATH"

    # Step 4: Build and Generate Quarkus Blog with Quarkus HTTP Root Path
    - name: Build & Generate Blog
      shell: bash
      run: |
        cd ${{ env.SITE_DIR }}
        ${{ inputs.maven-executable }} -B package quarkus:run \
          ${{ inputs.maven-build-args }} \
          -Dquarkus.http.root-path=${{ env.SITE_PATH }} \
          -Dsite.url=${{ env.SITE_URL }}
      env:
        QUARKUS_ROQ_GENERATOR_BATCH: true

    # Step 5: Setup GitHub Pages
    - name: Setup Pages
      if: ${{ inputs.github-pages == 'true' }}
      uses: actions/configure-pages@v5

    # Step 6: Upload Artifact to GitHub Pages
    - name: Upload Artifact
      if: ${{ inputs.github-pages == 'true' }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.SITE_DIR }}${{ inputs.artifact-path }}
