= Roq 1.7 - Asciidoc 🚀 and fragment search
:page-description: Roq 1.7 brings, Asciidoc as a top-level citizen, and greatly improve the search plugin.
:page-image: https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?q=80&w=3273&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
:page-tags: plugin, frontmatter, guide, asciidoc
:page-author: ia3andy
:page-draft:

The Asciidoc support was already available, but with this new release, we made it a Roq top level citizen:

* Support for Asciidoc headers to control the Roq data
* Includes
* Roq page and site attributes (urls, ...)
* `xref` are working out of the box for structured content such as docs
* Fine grained Asciidoc attributes (config, layout, page)
* Harmonization between Ruby and Java implementation
* Dynamic TOC support

👉 link:{site-path}docs/plugins/#plugin-asciidoc[The Roq Asciidoc plugin doc]

A few weeks ago, we added link:{site-path}posts/your-users-deserve-searching-capabilities/[support for search] as a plugin to Roq. I wasn't fully happy with the style and the fact that it was targetting the full page instead of the nearest fragment for the actual keyword.

I spend a bit of time on this and came up with a new way of indexing the content which slice the content based on fragments. Currently, it supports both Asciidoc and Markdown output.

Give it a try, it is enabled on this site. If you want this for your site:

👉 link:{site-path}docs/plugins/#plugin-asciidoc[The Roq Search plugin doc]