package io.quarkiverse.roq.plugin.hybrid.runtime;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;

import jakarta.inject.Inject;
import jakarta.inject.Singleton;

import org.eclipse.microprofile.config.ConfigProvider;
import org.jboss.logging.Logger;

import io.quarkiverse.roq.exception.RoqException;
import io.quarkiverse.roq.frontmatter.runtime.config.RoqFrontMatterConfigException;
import io.quarkiverse.roq.frontmatter.runtime.model.Page;

@Singleton
public class RoqCacheManager {

    private static final Logger LOG = Logger.getLogger(RoqCacheManager.class);

    private final RoqCacheStore store;
    private final RoqHybridConfig config;
    private final long ttlMillis;

    @Inject
    public RoqCacheManager(RoqHybridConfig config) {
        this.config = config;
        this.ttlMillis = config.cacheTtl().map(d -> d.toMillis()).orElse(0L);
        String buildId = config.cacheBuildId()
                .orElseGet(() -> ConfigProvider.getConfig().getValue("quarkus.uuid", String.class).substring(0, 8));
        if (config.cacheStore() == RoqHybridConfig.CacheStore.FILESYSTEM) {
            Path baseDir = config.cacheDir().map(Path::of)
                    .orElse(Path.of(System.getProperty("java.io.tmpdir"), "roq-hybrid-cache"));
            this.store = new FileSystemCacheStore(baseDir.resolve(buildId));
            cleanStaleBuildDirs(baseDir, buildId);
        } else {
            this.store = new MemoryCacheStore(config);
        }
    }

    public RoqCacheStore.CacheEntry get(String key, Page page) {
        RoqCacheStore.CacheEntry entry = store.get(key);
        if (entry != null && entry.isOutOfDate(getTtlMillis(page))) {
            store.invalidate(key);
            return null;
        }
        return entry;
    }

    public void put(String key, String value) {
        store.put(key, value);
    }

    public void putStartup(String key, String value) {
        store.putStartup(key, value);
    }

    public void invalidate(String key) {
        store.invalidate(key);
    }

    public void invalidateAll() {
        store.invalidateAll();
    }

    public long size() {
        return store.size();
    }

    public double hitRate() {
        if (store instanceof MemoryCacheStore memoryStore) {
            return memoryStore.hitRate();
        }
        return -1;
    }

    public RoqHybridConfig.CacheMode getCacheMode(Page page) {
        Object cachedValue = page.data("cache");
        if (cachedValue != null) {
            return RoqHybridConfig.CacheMode.fromString(String.valueOf(cachedValue));
        }
        return config.cacheMode();
    }

    public String cacheKey(Page page) {
        return page.source().template().generatedQuteId();
    }

    public long getTtlMillis(Page page) {
        if (getCacheMode(page) == RoqHybridConfig.CacheMode.STARTUP) {
            return 0;
        }
        Object pageTtl = page.data("cache-ttl");
        if (pageTtl != null) {
            try {
                String v = String.valueOf(pageTtl).trim().toUpperCase();
                if (!v.startsWith("P")) {
                    v = "PT" + v;
                }
                return Duration.parse(v).toMillis();
            } catch (Exception e) {
                throw new RoqFrontMatterConfigException(RoqException.builder("Invalid cache-ttl value")
                        .sourceInfo(page.source().template().file().toSourceInfo())
                        .detail("'%s' is not a valid duration".formatted(pageTtl))
                        .hint("Use formats like '30s', '5m', '1h', or ISO-8601 'PT5M'"));
            }
        }
        return ttlMillis;
    }

    private static void cleanStaleBuildDirs(Path baseDir, String currentBuildId) {
        try {
            if (!Files.exists(baseDir)) {
                return;
            }
            try (var dirs = Files.newDirectoryStream(baseDir, Files::isDirectory)) {
                for (Path dir : dirs) {
                    String name = dir.getFileName().toString();
                    if (!name.equals(currentBuildId) && isAutoGeneratedBuildId(name)) {
                        FileSystemCacheStore.deleteRecursively(dir);
                        LOG.infof("Cleaned stale cache directory: %s", name);
                    }
                }
            }
        } catch (IOException e) {
            LOG.warnf(e, "Failed to clean stale cache directories in %s", baseDir);
        }
    }

    private static boolean isAutoGeneratedBuildId(String name) {
        return name.matches("[0-9a-f]{8}");
    }

}
