package io.quarkiverse.roq.plugin.markdowntwin.runtime;

import java.util.Map;

/**
 * The twins the build produced: page resource path to twin resource path. Filled once at static init by
 * {@link MarkdownTwinRecorder}, read by {@link MarkdownTwinTemplateExtension}. A page that opted out or whose
 * conversion failed is absent, so nothing can advertise a twin that does not exist.
 * <p>
 * Generated by Claude Code.
 */
public final class MarkdownTwins {

    private static volatile Map<String, String> twins = Map.of();

    private MarkdownTwins() {
    }

    static void init(Map<String, String> value) {
        twins = value == null ? Map.of() : Map.copyOf(value);
    }

    /**
     * @param pageResourcePath the page's {@code RoqUrl#resourcePath()}
     * @return the twin's resource path, or null when the page has no twin
     */
    public static String twinOf(String pageResourcePath) {
        return pageResourcePath == null ? null : twins.get(pageResourcePath);
    }
}
