package io.quarkiverse.roq.plugin.markdowntwin.runtime;

import io.quarkiverse.roq.frontmatter.runtime.model.Page;
import io.quarkiverse.roq.frontmatter.runtime.model.RoqUrl;
import io.quarkus.arc.Unremovable;
import io.quarkus.qute.TemplateExtension;

/**
 * {@code page.markdownTwin}: the absolute URL of the page's Markdown twin, or null when the page has none (the page
 * opted out, or its conversion failed and no file was written). Templates use it to advertise the twin, so a page
 * never points at a twin that does not exist.
 * <p>
 * Generated by Claude Code.
 */
@Unremovable
@TemplateExtension
public class MarkdownTwinTemplateExtension {

    static String markdownTwin(Page page) {
        final RoqUrl url = page.url();
        if (url == null) {
            return null;
        }
        final String twin = MarkdownTwins.twinOf(url.resourcePath());
        return twin == null ? null : url.fromRoot(twin).absolute();
    }
}
