package io.quarkiverse.roq.plugin.markdowntwin.deployment;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import io.yupiik.asciidoc.model.Document;
import io.yupiik.asciidoc.parser.Parser;
import io.yupiik.asciidoc.parser.resolver.ContentResolver;

/**
 * Unit tests for the AsciiDoc-to-Markdown renderer and converter. Plain JUnit, no Quarkus.
 * <p>
 * Generated by Claude Code.
 */
class MarkdownRendererTest {

    @TempDir
    Path tmp;

    private static String md(String asciidoc) {
        return md(asciidoc, Map.of());
    }

    private static String md(String asciidoc, Map<String, String> attributes) {
        final Document document = new Parser(new HashMap<>(attributes)).parse(asciidoc,
                new Parser.ParserContext(ContentResolver.of(Path.of("."))));
        final MarkdownRenderer renderer = new MarkdownRenderer(attributes, null);
        renderer.visit(document);
        return renderer.result();
    }

    @Test
    void titleAndSections() {
        final String md = md("""
                = Page Title

                Intro paragraph.

                == First section

                Body text.

                === Nested

                More text.
                """);
        assertThat(md).startsWith("# Page Title\n\nIntro paragraph.\n\n");
        assertThat(md).contains("## First section\n\nBody text.\n\n");
        assertThat(md).contains("### Nested\n\nMore text.\n");
        assertThat(md).endsWith("\n").doesNotEndWith("\n\n");
    }

    @Test
    void fallbackTitleWhenTheSourceHasNoTitleLine() {
        final Document document = new Parser().parse("Just a paragraph.",
                new Parser.ParserContext(ContentResolver.of(Path.of("."))));
        final MarkdownRenderer renderer = new MarkdownRenderer(Map.of(), "From Front Matter");
        renderer.visit(document);
        assertThat(renderer.result()).isEqualTo("# From Front Matter\n\nJust a paragraph.\n");
    }

    @Test
    void inlineStyles() {
        final String md = md("Some *bold* and _italic_ and `mono` text.");
        assertThat(md).contains("**bold**").contains("*italic*").contains("`mono`");
    }

    @Test
    void links() {
        final String md = md("See https://roq.dev[the site] or https://example.org for more.");
        assertThat(md).contains("[the site](https://roq.dev)").contains("<https://example.org>");
    }

    @Test
    void crossReferencesPointAtSiblingTwins() {
        final String md = md("""
                = Doc

                [#pages]
                == Pages

                See xref:advanced.adoc#editor[the editor], <<pages,the pages section>> and <<pages>>.
                """);
        assertThat(md).contains("[the editor](../advanced/index.md#editor)");
        assertThat(md).contains("[the pages section](#pages)");
        assertThat(md).contains("[Pages](#pages)");
    }

    @Test
    void imagesUseImagesDir() {
        final String md = md("""
                = Doc
                :imagesdir: {site-path}images/docs

                image::layouts.webp[Roq layouts]

                Inline image:icon.svg[] here.
                """, Map.of("site-path", "/"));
        assertThat(md).contains("![Roq layouts](/images/docs/layouts.webp)");
        assertThat(md).contains("![icon](/images/docs/icon.svg)");
    }

    @Test
    void sourceBlockWithCallouts() {
        final String md = md("""
                .A title
                [source,yaml]
                ----
                site:
                  title: Roq <1>
                  url: https://roq.dev <2>
                ----
                <1> The site title.
                <2> The site URL.
                """);
        assertThat(md).contains("**A title**\n\n```yaml\n");
        assertThat(md).contains("title: Roq <1>\n");
        assertThat(md).contains("url: https://roq.dev <2>\n```\n\n1. The site title.\n2. The site URL.\n");
    }

    @Test
    void bareSourceBlockHasNoLanguage() {
        final String md = md("""
                [source]
                ----
                plain text
                ----
                """);
        assertThat(md).isEqualTo("```\nplain text\n```\n");
    }

    @Test
    void lists() {
        final String md = md("""
                * first
                * second
                ** nested

                . one
                . two

                * [x] done
                * [ ] todo
                """);
        assertThat(md).contains("- first\n- second\n  - nested\n");
        assertThat(md).contains("1. one\n2. two\n");
        assertThat(md).contains("- [x] done\n- [ ] todo\n");
    }

    @Test
    void descriptionList() {
        final String md = md("""
                CPU:: The brain.
                RAM:: The memory.
                """);
        assertThat(md).contains("**CPU**\\\nThe brain.\n\n**RAM**\\\nThe memory.\n");
    }

    @Test
    void admonitions() {
        final String md = md("""
                NOTE: Mind the gap.

                [TIP]
                ====
                Use the plugin.
                ====

                [WARNING]
                --
                Open block style.
                --
                """);
        assertThat(md).contains("> [!NOTE]\n> Mind the gap.\n");
        assertThat(md).contains("> [!TIP]\n> Use the plugin.\n");
        assertThat(md).contains("> [!WARNING]\n> Open block style.\n");
    }

    @Test
    void table() {
        final String md = md("""
                .Options
                [cols="1,1",options="header"]
                |===
                |Name |Value

                |a
                |1 \\| one

                |b
                |2
                |===
                """);
        assertThat(md).contains("**Options**\n\n| Name | Value |\n| --- | --- |\n| a | 1 \\| one |\n| b | 2 |\n");
    }

    @Test
    void quoteAndCollapsible() {
        final String md = md("""
                [quote, Someone, Somewhere]
                ____
                Words of wisdom.
                ____

                .Show me
                [%collapsible]
                ====
                Hidden text.
                ====
                """);
        assertThat(md).contains("> Words of wisdom.\n>\n> — Someone, Somewhere\n");
        assertThat(md).contains("<details>\n<summary>Show me</summary>\n\nHidden text.\n\n</details>\n");
    }

    @Test
    void attributesResolveOrStayLiteral() {
        final String md = md("""
                = Doc
                :product: Roq

                {product} lives at {site-url}; {missing} stays and so does {page.title}.
                """, Map.of("site-url", "https://roq.dev"));
        // The parser turns the site URL into a bare link and swallows the semicolon; the renderer moves it back out.
        assertThat(md).contains("Roq lives at <https://roq.dev>; {missing} stays and so does {page.title}.");
    }

    @Test
    void conditionals() {
        final String md = md("""
                ifdef::absent[]
                hidden text
                endif::[]
                ifndef::absent[]
                shown text
                endif::[]
                ifdef::present[]
                present text
                endif::[]
                """, Map.of("present", ""));
        assertThat(md).contains("shown text").contains("present text").doesNotContain("hidden text");
    }

    @Test
    void passthroughHorizontalRuleAndKbd() {
        final String md = md("""
                ++++
                <b>raw html</b>
                ++++

                '''

                Press kbd:[Ctrl+C] now.
                """);
        assertThat(md).contains("<b>raw html</b>\n\n---\n\n");
        assertThat(md).contains("Press <kbd>Ctrl</kbd>+<kbd>C</kbd> now.");
    }

    @Test
    void restoreCalloutMarkersOnlyTouchesTrailingMarkers() {
        assertThat(MarkdownRenderer.restoreCalloutMarkers("a (1)\nb (1) (2)\nf(x) = (1) + 1\n", Set.of(1, 2)))
                .isEqualTo("a <1>\nb <1> <2>\nf(x) = (1) + 1\n");
    }

    @Test
    void restoreCalloutMarkersKeepsCodeEndingInParentheses() {
        assertThat(MarkdownRenderer.restoreCalloutMarkers(
                ".statusCode(200)\n@Bulkhead(1)\ncall(); // (1)\nkey: value #(2)\nd (3)\n", Set.of(1, 2)))
                .isEqualTo(".statusCode(200)\n@Bulkhead(1)\ncall(); // <1>\nkey: value #<2>\nd (3)\n");
    }

    @Test
    void sourceBlockEndingInParenthesesKeepsTheCode() {
        final String md = md("""
                [source,java]
                ----
                given().get("/hello") <1>
                  .then()
                  .statusCode(200)
                @Priority(1) <2>
                @Bulkhead(1)
                ----
                <1> Call the endpoint.
                <2> Order the bean.
                """);
        assertThat(md)
                .contains("given().get(\"/hello\") <1>\n  .then()\n  .statusCode(200)\n@Priority(1) <2>\n@Bulkhead(1)\n```");
    }

    @Test
    void converterResolvesIncludesLikeTheBlog() throws IOException {
        final Path includes = Files.createDirectories(tmp.resolve("includes"));
        final Path docs = Files.createDirectories(tmp.resolve("content/docs"));
        Files.writeString(includes.resolve("attributes.adoc"), """
                :notitle:
                :imagesdir: {site-path}images/docs
                """);
        Files.writeString(includes.resolve("edit-contrib.adoc"),
                """
                        NOTE: If you find an issue, link:https://github.com/x/edit/main/blog/content/docs/{doc-name}.adoc[edit this document].
                        """);
        Files.writeString(includes.resolve("directory-structure.adoc"), """
                == Directory Structure

                [source,yaml]
                ----
                content: pages <1>
                ----
                <1> The pages.
                """);
        final Path page = docs.resolve("basics.adoc");
        Files.writeString(page, """
                ---
                layout: doc
                ---
                = Roq the basics
                include::../../includes/attributes.adoc[]
                :doc-name: basics

                include::../../includes/edit-contrib.adoc[]

                By default, your site files live in the project root.

                include::../../includes/directory-structure.adoc[]
                """);

        final Optional<String> result = AsciidocMarkdownConverter.convert(page, Map.of("site-path", "/"), null);

        assertThat(result).isPresent();
        final String md = result.get();
        assertThat(md).startsWith("# Roq the basics\n\n");
        assertThat(md).contains("> [!NOTE]");
        assertThat(md).contains("[edit this document](https://github.com/x/edit/main/blog/content/docs/basics.adoc)");
        assertThat(md).contains("## Directory Structure\n\n```yaml\ncontent: pages <1>\n```\n\n1. The pages.\n");
        assertThat(md).doesNotContain("include::").doesNotContain(":imagesdir:").doesNotContain("{doc-name}")
                .doesNotContain("layout: doc");
    }

    @Test
    void converterDegradesCalloutsTheParserRejects() throws IOException {
        final Path page = tmp.resolve("callouts.adoc");
        Files.writeString(page, """
                = Callouts

                [source,properties]
                ----
                quarkus.arc.exclude-types=org.acme.Foo,org.acme.*,Bar <1><2><3>
                ----
                <1> Exclude the type.
                <2> Exclude the package.
                <3> Exclude by simple name.
                """);
        final Optional<String> result = AsciidocMarkdownConverter.convert(page, Map.of(), null);
        assertThat(result).isPresent();
        assertThat(result.get()).contains("```properties").contains("1. Exclude the type.")
                .contains("3. Exclude by simple name.");
    }

    @Test
    void converterSurvivesAMissingInclude() throws IOException {
        final Path page = tmp.resolve("missing.adoc");
        Files.writeString(page, """
                = Missing include

                include::nowhere.adoc[]

                Still here.
                """);
        final Optional<String> result = AsciidocMarkdownConverter.convert(page, Map.of(), null);
        assertThat(result).isPresent();
        assertThat(result.get()).contains("# Missing include").contains("Still here.");
    }

    @Test
    void converterReturnsEmptyForAMissingFile() {
        assertThat(AsciidocMarkdownConverter.convert(tmp.resolve("absent.adoc"), Map.of(), null)).isEmpty();
    }

    @Test
    void neutralizeCalloutsRewritesItemsAndMarkers() {
        assertThat(AsciidocMarkdownConverter.neutralizeCallouts(List.of("code <1><2>", "<1> one", "<2> two", "plain")))
                .containsExactly("code (1)(2)", "1. one", "2. two", "plain");
    }
}
