package io.quarkiverse.roq.plugin.markdowntwin.deployment;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

/**
 * Where twins live and how twins link to each other: inside the page's directory for a directory-style URL, beside the
 * file otherwise.
 * <p>
 * Generated by Claude Code.
 */
class TwinPathTest {

    @Test
    void directoryStyleUrlGetsIndexMdInsideTheDirectory() {
        assertThat(RoqPluginMarkdownTwinProcessor.twinPath("docs/basics/")).isEqualTo("docs/basics/index.md");
        assertThat(RoqPluginMarkdownTwinProcessor.twinPath("posts/welcome-to-roq/"))
                .isEqualTo("posts/welcome-to-roq/index.md");
    }

    @Test
    void fileStyleUrlGetsMdAppended() {
        assertThat(RoqPluginMarkdownTwinProcessor.twinPath("404.html")).isEqualTo("404.html.md");
    }

    @Test
    void siteRootHasNoTwin() {
        assertThat(RoqPluginMarkdownTwinProcessor.twinPath("")).isNull();
        assertThat(RoqPluginMarkdownTwinProcessor.twinPath("/")).isNull();
        assertThat(RoqPluginMarkdownTwinProcessor.twinPath(null)).isNull();
    }

    @Test
    void crossPageLinksPointAtTheOtherPagesTwin() {
        assertThat(MarkdownRenderer.twinOf("advanced.adoc")).isEqualTo("../advanced/index.md");
        assertThat(MarkdownRenderer.twinOf("./advanced.adoc")).isEqualTo("../advanced/index.md");
        assertThat(MarkdownRenderer.twinOf("guides/advanced.adoc")).isEqualTo("../guides/advanced/index.md");
        assertThat(MarkdownRenderer.twinOf("/docs/advanced.adoc")).isEqualTo("/docs/advanced/index.md");
    }
}
