package io.quarkiverse.roq.plugin.markdowntwin.deployment;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.Test;

/**
 * Which pages the configured include and exclude patterns keep in scope.
 * <p>
 * Generated by Claude Code.
 */
class TwinScopeTest {

    private static TwinScope scope(List<String> include, List<String> exclude) {
        return TwinScope.of(new MarkdownTwinConfig() {
            @Override
            public boolean enabled() {
                return true;
            }

            @Override
            public Optional<List<String>> include() {
                return include == null ? Optional.empty() : Optional.of(include);
            }

            @Override
            public Optional<List<String>> exclude() {
                return exclude == null ? Optional.empty() : Optional.of(exclude);
            }
        });
    }

    @Test
    void everythingIsInScopeWhenNothingIsConfigured() {
        final TwinScope scope = scope(null, null);
        assertThat(scope.includes("guides/http-reference")).isTrue();
        assertThat(scope.includes("posts/welcome-to-roq/")).isTrue();
    }

    @Test
    void includeLimitsToTheMatchingTrees() {
        final TwinScope scope = scope(List.of("/guides/**", "/posts/**"), null);
        assertThat(scope.includes("guides/http-reference")).isTrue();
        assertThat(scope.includes("posts/welcome-to-roq/")).isTrue();
        assertThat(scope.includes("version/3.15/guides/http-reference")).isFalse();
        assertThat(scope.includes("about")).isFalse();
    }

    @Test
    void excludeWinsOverInclude() {
        final TwinScope scope = scope(List.of("/guides/**"), List.of("/guides/all-config"));
        assertThat(scope.includes("guides/http-reference")).isTrue();
        assertThat(scope.includes("guides/all-config")).isFalse();
    }

    @Test
    void excludeAloneKeepsTheRestInScope() {
        final TwinScope scope = scope(null, List.of("/version/**"));
        assertThat(scope.includes("guides/http-reference")).isTrue();
        assertThat(scope.includes("version/3.15/guides/http-reference")).isFalse();
    }

    @Test
    void leadingSlashIsOptionalOnBothSides() {
        assertThat(scope(List.of("guides/**"), null).includes("/guides/http-reference")).isTrue();
        assertThat(scope(List.of("/guides/**"), null).includes("guides/http-reference")).isTrue();
        assertThat(scope(List.of("glob:/guides/**"), null).includes("guides/http-reference")).isTrue();
    }

    @Test
    void singleStarDoesNotCrossASlashButDoubleStarDoes() {
        assertThat(scope(List.of("/guides/*"), null).includes("guides/http-reference")).isTrue();
        assertThat(scope(List.of("/guides/*"), null).includes("guides/nested/page")).isFalse();
        assertThat(scope(List.of("/guides/**"), null).includes("guides/nested/page")).isTrue();
    }

    @Test
    void anExplicitRegexIsHonoured() {
        final TwinScope scope = scope(List.of("regex:guides/.*"), null);
        assertThat(scope.includes("guides/http-reference")).isTrue();
        assertThat(scope.includes("about")).isFalse();
    }

    @Test
    void blankPatternsAreIgnoredRatherThanMatchingNothing() {
        final TwinScope scope = scope(List.of("  "), null);
        assertThat(scope.includes("guides/http-reference")).isTrue();
    }
}
