= Quarkus Roq

include::./includes/attributes.adoc[]

The Roq Static Site Generator extension allows to easily create a static website or blog using Quarkus super-powers.

Roq already includes a set of extensions which can also be used standalone:

* xref:quarkus-roq-data.adoc[*Roq Data*]: Use json/yaml files content from your templates and articles with type safety.
* xref:quarkus-roq-frontmatter.adoc[*Roq FrontMatter*]:  Create a website from your Markdown/Asciidoc/Html pages using FrontMatter headers (url, layout, seo, data).
* xref:quarkus-roq-generator.adoc[*Roq Generator*]: Command to run any Quarkus web application and extract it in a directory as purely static files (html and assets).

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.roq:quarkus-roq` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.roq</groupId>
    <artifactId>quarkus-roq</artifactId>
    <version>{project-version}</version>
</dependency>
----

include::includes/getting-started-frontmatter.adoc[]

[[custom-site-dir]]
== Configure a custom Roq site directory

It can be located in a resource directory such as `src/main/resources/my-site`:
[source,properties]
.application.properties
----
quarkus.roq.resource-dir=my-site
----

or in your project directory such as `my-site`:
[source,properties]
.application.properties
----
quarkus.roq.dir=my-site
----







[[extension-configuration-reference]]
== Extension Configuration Reference


include::includes/quarkus-roq.adoc[leveloffset=+1, opts=optional]
