include::./includes/attributes.adoc[]

= Quarkus Roq Generator

It provides a command to run any Quarkus web application and extract it in a directory as purely static files (html and assets).

CAUTION: Roq Generator is already included as part of the Roq Static Site Generator extension `io.quarkiverse.roq:quarkus-roq`, Follow <<standalone-installation>> section to use it standalone.

== Generating your static site

You can generate your static site using:

[source,shell]
----
QUARKUS_ROQ_GENERATOR_BATCH=true mvn package quarkus:run -DskipTests
----

By default, it will generate the static site in the `target/roq` directory.

TIP: When used within the Roq Static Site Generator extension, it is already pre-configured to generate the whole site (which can be disabled with `site.generator=false`). In standalone mode, by default, only the `/` (index.html) and `static/**` will be generated. Follow the next section to configure the selection.


You can now try or deploy your static website with any static file server. We provide a small tool to try it:
[source,shell]
----
$ jbang app install --verbose --fresh --force roq@quarkiverse/quarkus-roq
$ roq                                                                                                                         decks->!+(ia3andy/decks)
Serving: target/roq/
Server started on port http://localhost:8181
----

TIP: at any time you can open the dev-ui to see the Roq Generator selection.


== Github Pages configuration

You can configure Roq to deploy Github Pages, Netlify, or any static website server.

Check how the Roq blog is deployed on GitHub pages https://github.com/quarkiverse/quarkus-roq/blob/main/.github/workflows/deploy-blog.yml[here].


== Advanced Usage

=== Configure the static selection

You can configure application paths which should be generated as static files from the Quarkus configuration:
[source,properties]
.application.properties
----
quarkus.roq.generator.paths=/,/static/**,/bar/
----

TIP: By convention paths ending with `/` such as `/bar/` are considered as html pages and with generate html pages such as `/bar/index.html`.

CAUTION: The glob syntax is only working with fixed paths. Paths which uses query params or path params should be either manually entered or provided at runtime from the Java code.

You can also manually specify the generated output path:
[source,properties]
.application.properties
----
quarkus.roq.generator.custom-paths."/api/foo"=/foo.json
----

=== Configure the dynamic selection

You need to produce a `RoqSelection` singleton from your application:

[source,java]
----

    @Produces
    @Singleton
    RoqSelection produce() {
        return new RoqSelection(List.of(
                SelectedPath.builder().html("/roq?name=foo").build(), // <1>
                SelectedPath.builder().html("/blog/hello-roq").build(), // <2>
                SelectedPath.builder().path("/api/hello?name=foo").outputPath("/hello-foo.json").build()));  // <3>
    }
----
<1> Using `.html()` means we want to generate an html page from `roq?name=foo` content, when unspecified we generate the output path automatically, in that case it would be `/roq-name-foo/index.html`.
<2> in that case it will generate `/blog/hello-roq/index.html`.
<3> It is also possible to manually specify the output path. In that case it will generate `/hello-foo.json` from `/api/hello?name=foo` content.

TIP: Use `@Transactional` if you need to iterate through database entities to prepare your selection. For example if the blog post ids are stored in a database.

include::includes/github-pages.adoc[]

[[standalone-installation]]
== Standalone installation

NOTE: It is included and pre-configured as part of the Roq Static Site Generator extension `io.quarkiverse.roq:quarkus-roq`.

You can also use it standalone on any Quarkus application. If you want to use this extension standalone, you need to add the `io.quarkiverse.roq:quarkus-roq-generator` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.roq</groupId>
    <artifactId>quarkus-roq-generator</artifactId>
    <version>{project-version}</version>
</dependency>
----

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-roq-generator.adoc[leveloffset=+1, opts=optional]