---
title: Advanced Stuff
layout: doc
---
{#include partials/doc/doc-attributes.adoc/}

= Roq Advanced Stuff

{#include partials/doc/edit-contrib.adoc name="advanced"/}

[#pagination]
== Pagination

Adding pagination to your Roq site is an easy way to improve content
navigation. Let’s walk through how to implement pagination and customize
its behavior in your site.

=== Step 1: Iterate on the paginated collection

First, include the following in your FrontMatter header on the page which will
iterate on the paginated collection:

[source,yaml]
----
paginate: posts
----

Next, in your template, loop through the paginated posts using:

{|
[source,html]
----
{#for post in site.collections.posts.paginated(page.paginator)} // <1>
<article class="post">
  ...
</article>
{/for}

{#include includes/pagination.html/}
----
<1> Calling `.paginated(page.paginator)` will resolve to the posts for the computed page.
|}

=== Step 2: Including Pagination Controls

To add pagination controls, use the provided `fm/pagination.html` in your own `_includes/pagination.html`:

{|
[source,html]
----
{#include fm/pagination.html}
{#newer}<i class="fa fa-long-arrow-left" aria-hidden="true"></i>{/newer}
{#older}<i class="fa fa-long-arrow-right" aria-hidden="true"></i>{/older}
{/include}
----
|}

NOTE: If you want to write your own controls, find inspiration in the FM sources https://github.com/quarkiverse/quarkus-roq/tree/main/roq-frontmatter/runtime/src/main/resources/templates/fm/pagination.html[fm/pagination.html].

Just by doing so, Roq will generate a bunch of pages based on the pagination setting. For example with a pagination size of 4 and with 9 posts, you would get:

* `index.html` (posts 1 to 4)
* `posts/page-2` (posts 5 to 8)
* `posts/page-3` (post 9)

NOTE: the first page uses the declaring page link.


You can further customize your pagination by setting the page size and link format:

[source,yaml]
----
paginate:
  size: 4
  collection: posts
  link: posts/page-:page
----

With these steps, you can create a flexible pagination system to improve your site’s navigation.

== SEO

Incorporating search engine optimization (SEO) is as simple as inserting this tag into your `<head>` section:

{|
[source,html]
----
<head>
{#seo page site /}
</head>
----
|}

It will automatically use the FrontMatter data to fill the tags.

[source,html]
----
<title>My Blog Post</title>
<meta name="author" content="ia3andy" />
<meta name="generator" content="Quarkus Roq v1.0.0" />
<meta property="article:author" content="ia3andy" />
<meta property="article:published_time" content="2024-09-23T12:00Z[Etc/UTC]" />
<meta property="og:image" content="https://images.unsplash.com/photo.webp" />
<meta property="og:locale" content="en-US" />
<meta property="og:type" content="article" />
----

== RSS

Incorporating and RSS feed of your posts is as simple as inserting this tag into your `<head>` section:

{|
[source,html]
----
<head>
{#rss site /}
</head>
----
|}

It will automatically use the FrontMatter data generate an RSS feed link.

[source,html]
----
<link rel="alternate" type="application/rss+xml" title="Your Blog" href="/rss.xml"/>
----

It will automatically utilize the Frontmatter data from all your blog posts to generate a valid Atom RSS feed link at `rss.xml`. Ensure you create an `rss.xml` file at the root of your site and include this single line of code:

{|
[source,html]
----
{#include fm/rss.html}
----
|}


== Themes

[#overriding-theme]
=== Overriding theme layouts

In Roq, you can override theme layouts by inserting an extra layout layer. This allows you to override only specific sections of the theme layout, without duplicating the entire layout structure.

TIP: Roq layouts are leveraging https://quarkus.io/guides/qute-reference#include_helper[Qute includes] under the hood. It is possible to define insert sections which can define overridable default content.

For example, let’s override the `roq-default` theme's main layout so that our customizations apply everywhere it is used.

{|
.templates/layouts/roq-default/main.html
[source,html]
----
---
layout: theme-layouts/roq-default/main // <1>
---

{#insert /} // <2>

{#description} // <3>
Here I can override the description section
{/}

{#footer}
<footer>
And here the footer
</footer>
{/}
----
<1> *Inherits from the theme layout:* This layout uses the original theme layout (`roq-default/main`) as a base.
<2> *Inheritance mechanism:* `{#insert /}` ensures that this layout will inherit sections defined in the theme layout.
<3> *Override specific sections:* You can override individual sections such as `description` and `footer` without affecting other parts of the layout.
|}

Now, everywhere `layouts: :theme/main` (even in the theme), your override will be used.

=== Developing a theme

To develop a theme, create a Maven module which will contain the theme layouts, partials, scripts and styles.

[source]
----
.
└── main
    ├── resources
    │   ├── application.properties
    │   └── templates
    │       ├── partials
    │       │   └── roq-default // <1>
    │       │       ├── head.html
    │       │       ├── pagination.html
    │       │       ├── sidebar-about.html
    │       │       ├── sidebar-contact.html
    │       │       ├── sidebar-copyright.html
    │       │       └── sidebar-menu.html
    │       └── theme-layouts // <2>
    │           └── roq-default
    │               ├── default.html
    │               ├── index.html
    │               ├── main.html
    │               ├── page.html
    │               ├── post.html
    │               └── tag.html
    └── web
        ├── roq.js
        ├── roq.scss
----
<1> You can add partials for your theme, they need to be located in a directory with the theme name.
<2> Layouts needs to be declared in the `theme-layouts` so that they can be overridden by consuming websites.

Same as for a site, script and styles can either be added to `src/main/resoucres/META-INF/resources` or bundled using Maven esbuild plugin:

.pom.xml
[source,xml]
----
             <plugin>
                <groupId>io.mvnpm</groupId>
                <artifactId>esbuild-maven-plugin</artifactId>
                <version>0.0.2</version>
                <executions>
                    <execution>
                        <id>esbuild</id>
                        <goals>
                            <goal>esbuild</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <entryPoint>roq.js</entryPoint> // <1>
                </configuration>
                <dependencies> // <2>
                    <dependency>
                        <groupId>org.mvnpm.at.fortawesome</groupId>
                        <artifactId>fontawesome-free</artifactId>
                        <version>6.6.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.mvnpm.at.fontsource</groupId>
                        <artifactId>pt-serif</artifactId>
                        <version>5.1.0</version>
                    </dependency>
                </dependencies>
            </plugin>
----
<1> Add your esbuild entrypoint from `src/main/resources/web`
<2> Add mvnpm or webjars dependencies

This bundle will be available in `/static/bundle/roq.js` and `/static/bundle/roq.css` which can be used in your theme html `<head>`

Create an application.properties:

.src/main/resources/application.properties
[source,properties]
----
site.theme=roq-default // <1>
----
<1> Thanks to this, all call to `layout: :theme/...` will automatically refer to this theme.

[#links]
== Links & Urls

The output location of pages and documents is determined by the FrontMatter `link` key. This `link` value can include placeholders, which will be dynamically replaced with relevant values for routing.

TIP: Those links are also available in the Qute data to allow <<roq-url>>.

[#link-placeholders]
=== Link placeholders

|===
| Type of page | Placeholder  | Description | Example Output

| All
| `:path`
| The file path of the page, slugified (converted to a URL-friendly format) without the extension.
| `my-page`, `search` or `docs/my-doc`

| All
| `:slug`
| The slugified title of the page, derived from the title. Defaults to the `slug` property in data, if available or using the slugified title, falling back to the file name.
| `my-page-title`

| All
| `:ext`
| The file extension with the dot. Empty for all files with html output (md, asciidoc, html, ...).
| `.json`

| All
| `:ext!`
| Force the output file extension.
| `.html`, `.json`

| All
| `:year`
| The year of the page’s date or the current year if the date is not available.
| `2024`

| All
| `:month`
| The month (formatted as two digits) of the page’s date or the current month if the date is not available.
| `10`

| All
| `:day`
| The day (formatted as two digits) of the page’s date or the current day if the date is not available.
| `28`

| Document
| `:collection`
| Represents the collection to which the document belongs, such as a specific category or folder name.
| `blog`, `articles`, `recipes`

| Paginated
| `:page`
| Represents the current page.
| `1`, `2`
|===


Default link value:

* for pages: `/:path:ext`.
* for documents: `/:collection/:slug/`.
* for paginated page: `/:collection/page:page/`.

TIP: You can define `link` in a layout to affect all the pages using that layout.

[#roq-url]
=== Creating links between your pages

The pages links are automatically converted to urls by Roq, they are available in the `site.url` and the `page.url` variables. This makes creating links very easy:

{|
[source,html]
----
<a href="{site.url}">Back to main page</a>
----
or to get the next page url in a document:

[source,html]
----
<a href="{page.next.url}">{page.next.title}</a>
----

or when iterating on documents:

[source,html]
----
{#for post in site.collections.posts}
  <a href="{post.url}">{post.title}</a>
{/for}
----

or also to manually retrieve a page url with `site.page(sourcePath)`:

[source,html]
----
<a href="{site.page('foo.html').url}">{site.page('foo.html').title}</a>
----
|}

TIP: By default, url will be rendered as relative from the site root. You can also get the full absolute url (i.e. from `http(s)://`) by using `absolute` on any url (e.g. `\{site.url.absolute}`).

=== Manual linking

Sometimes, you want to create a link for a page without holding the variable, in this case, you can use `site.url(relativePath)` which will be automatically resolved from the site root path.

== Site Configuration

Site configuration is done in `config/application.properties` (or `src/main/resources/application.properties`):


{#include partials/doc/configs/quarkus-roq-frontmatter_site.adoc /}