package io.quarkiverse.roq.plugin.asciidoctorj.test;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Set;

import org.junit.jupiter.api.Test;

import io.quarkiverse.roq.plugin.asciidoctorj.runtime.AsciidocJInclude;

// Generated by Claude Code
public class AsciidocJIncludeHandlesTest {

    @Test
    void shouldAlwaysHandleAdocFiles() {
        var include = new AsciidocJInclude(Set.of());
        assertThat(include.handles("intro.adoc")).isTrue();
        assertThat(include.handles("path/to/chapter.asciidoc")).isTrue();
    }

    @Test
    void shouldHandleConfiguredExtensions() {
        var include = new AsciidocJInclude(Set.of(".java", ".xml"));
        assertThat(include.handles("MyApp.java")).isTrue();
        assertThat(include.handles("path/to/pom.xml")).isTrue();
    }

    @Test
    void shouldRejectUnconfiguredExtensions() {
        var include = new AsciidocJInclude(Set.of(".java"));
        assertThat(include.handles("config.yaml")).isFalse();
        assertThat(include.handles("app.properties")).isFalse();
    }

    @Test
    void shouldRejectUrls() {
        var include = new AsciidocJInclude(Set.of(".java", ".html"));
        assertThat(include.handles("https://example.com/file.java")).isFalse();
        assertThat(include.handles("http://example.com/page.html")).isFalse();
        assertThat(include.handles("ftp://server/file.txt")).isFalse();
        assertThat(include.handles("mailto:user@example.com")).isFalse();
    }

    @Test
    void shouldRejectExtensionlessFiles() {
        var include = new AsciidocJInclude(Set.of(".java", ".txt"));
        assertThat(include.handles("Makefile")).isFalse();
        assertThat(include.handles("Dockerfile")).isFalse();
    }

    @Test
    void shouldHandleTargetsWithAttributePlaceholders() {
        var include = new AsciidocJInclude(Set.of(".java"));
        // After attribute resolution, the target looks like a normal path
        assertThat(include.handles("examples/src/main/java/MyApp.java")).isTrue();
    }
}
