site.url=http://localhost:8080
quarkus.roq.plugin.og-image.include-paths=/
quarkus.roq.plugin.og-image.collections=posts
quarkus.roq.plugin.og-image.output-prefix=/og
quarkus.roq.plugin.og-image.site-name=OG Test Site
quarkus.roq.plugin.og-image.exclude-paths=/posts/tag/
