site.url=http://localhost:8080
quarkus.roq.plugin.og-card.include-paths=/
quarkus.roq.plugin.og-card.collections=posts
quarkus.roq.plugin.og-card.output-prefix=/og
quarkus.roq.plugin.og-card.site-name=OG Test Site
quarkus.roq.plugin.og-card.exclude-paths=/posts/tag/
