quarkus.log.level=WARN
quarkus.log.category."io.quarkus.config".level=ERROR
quarkus.banner.enabled=false
quarkus.package.jar.type=uber-jar
quarkus.config.sources.system-only=true
quarkus.arc.detect-unused-false-positives=false
quarkus.native.resources.includes=quarkus.properties
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.maven.wagon.shared.http.AbstractHttpClientWagon
quarkus.native.enable-https-url-handler=true
