name: Build PR Preview

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.txt'
      - '.all-contributorsrc'
jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Build Roq
        run: mvn -B clean install --file pom.xml -DskipTests -Dno-format

      - name: Store PR id
        run: |
          echo ${{ github.event.number }} > ./docs/target/generated-docs/pr-id.txt

      - name: Publishing docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs/target/generated-docs
          retention-days: 3

      - name: Build blog
        uses: ./
        with:
          github-pages: false
          site-directory: 'blog'
          site-future: 'true'
          maven-executable: 'mvn'

      - name: Publishing blog
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: ./blog/target/roq
          retention-days: 3