package io.quarkiverse.roq.plugin.markdowntwin.deployment;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Pattern;

import org.jboss.logging.Logger;

import io.quarkiverse.roq.frontmatter.deployment.util.RoqFrontMatterTemplateUtils;
import io.yupiik.asciidoc.model.Document;
import io.yupiik.asciidoc.parser.Parser;
import io.yupiik.asciidoc.parser.resolver.RelativeContentResolver;

/**
 * Converts one AsciiDoc source file to Markdown in-process: strip the Roq front matter, parse with the pure-Java
 * {@code asciidoc-java} parser (which resolves {@code include::} directives while parsing), then render with
 * {@link MarkdownRenderer}.
 * <p>
 * The conversion never fails a build: any problem is logged at WARN and the caller gets an empty result, so the page
 * simply has no twin.
 * <p>
 * Generated by Claude Code.
 */
public final class AsciidocMarkdownConverter {

    private static final Logger LOG = Logger.getLogger(AsciidocMarkdownConverter.class);

    private static final Pattern CALLOUT_ITEM = Pattern.compile("^<(\\d+)> ");
    private static final Pattern CALLOUT_MARKER = Pattern.compile("<(\\d+)>");

    private AsciidocMarkdownConverter() {
    }

    /**
     * @param source the AsciiDoc file on disk (front matter allowed)
     * @param siteAttributes attributes the site provides ({@code site-url}, {@code page-url}, ...)
     * @param fallbackTitle title to use when the document has no title line
     * @return the Markdown, or empty when the page cannot be converted
     */
    public static Optional<String> convert(Path source, Map<String, String> siteAttributes, String fallbackTitle) {
        if (source == null || !Files.isRegularFile(source)) {
            LOG.warnf("Markdown twin: AsciiDoc source is not a readable file, skipping: %s", source);
            return Optional.empty();
        }
        final Map<String, String> attributes = new LinkedHashMap<>();
        if (siteAttributes != null) {
            attributes.putAll(siteAttributes);
        }
        try {
            final String content = RoqFrontMatterTemplateUtils
                    .stripFrontMatter(Files.readString(source, StandardCharsets.UTF_8));
            final List<String> lines = content.lines().toList();
            Document document;
            try {
                document = parse(source, lines, attributes);
            } catch (RuntimeException e) {
                if (!isCalloutMismatch(e)) {
                    throw e;
                }
                // Asciidoctor accepts callout lists that do not match the markers one to one (for example several
                // markers on one line); the parser does not. Degrade the callouts to a plain numbered list instead of
                // losing the whole page.
                LOG.debugf("Markdown twin: %s has callout markers the parser rejects, retrying with plain callouts", source);
                document = parse(source, neutralizeCallouts(lines), attributes);
            }
            final MarkdownRenderer renderer = new MarkdownRenderer(attributes, fallbackTitle);
            renderer.visit(document);
            return Optional.of(renderer.result());
        } catch (IOException | RuntimeException e) {
            LOG.warnf(e, "Markdown twin: AsciiDoc conversion failed for %s, skipping", source);
            return Optional.empty();
        }
    }

    static Document parse(Path source, List<String> lines, Map<String, String> attributes) {
        final Parser parser = new Parser(attributes);
        return parser.parse(source, lines, new Parser.ParserContext(new LenientPathResolver(source.getParent())));
    }

    static boolean isCalloutMismatch(Throwable failure) {
        for (Throwable t = failure; t != null; t = t.getCause()) {
            final String message = t.getMessage();
            if (message != null && message.toLowerCase(Locale.ROOT).contains("callout")) {
                return true;
            }
            if (t.getCause() == t) {
                break;
            }
        }
        return false;
    }

    /** Turns {@code <1> text} callout items into list items and in-code {@code <1>} markers into {@code (1)}. */
    static List<String> neutralizeCallouts(List<String> lines) {
        final List<String> result = new ArrayList<>(lines.size());
        for (String line : lines) {
            final String item = CALLOUT_ITEM.matcher(line).replaceFirst("$1. ");
            result.add(CALLOUT_MARKER.matcher(item).replaceAll("($1)"));
        }
        return result;
    }

    /**
     * Resolves includes relative to the including file, then relative to the page directory. A missing include is
     * logged and skipped so that the rest of the page still gets a twin.
     */
    static final class LenientPathResolver implements RelativeContentResolver {

        private final Path base;

        LenientPathResolver(Path base) {
            this.base = base == null ? Path.of(".") : base;
        }

        @Override
        public Optional<RelativeContentResolver.Resolved> resolve(Path parent, String ref, Charset charset) {
            final Path relative = Path.of(ref);
            final Path target;
            if (relative.isAbsolute()) {
                target = relative;
            } else if (parent != null && parent.getParent() != null) {
                target = parent.getParent().resolve(relative).normalize();
            } else {
                target = base.resolve(relative).normalize();
            }
            if (!Files.isRegularFile(target)) {
                LOG.warnf("Markdown twin: include '%s' not found (from %s), continuing without it", ref,
                        parent == null ? base : parent);
                return Optional.of(new RelativeContentResolver.Resolved(target, List.of()));
            }
            try {
                return Optional.of(new RelativeContentResolver.Resolved(target,
                        Files.readAllLines(target, charset == null ? StandardCharsets.UTF_8 : charset)));
            } catch (IOException e) {
                LOG.warnf(e, "Markdown twin: include '%s' could not be read, continuing without it", target);
                return Optional.of(new RelativeContentResolver.Resolved(target, List.of()));
            }
        }
    }
}
