package io.quarkiverse.roq.plugin.markdowntwin.deployment;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import io.yupiik.asciidoc.model.Admonition;
import io.yupiik.asciidoc.model.Anchor;
import io.yupiik.asciidoc.model.Attribute;
import io.yupiik.asciidoc.model.Body;
import io.yupiik.asciidoc.model.CallOut;
import io.yupiik.asciidoc.model.Code;
import io.yupiik.asciidoc.model.ConditionalBlock;
import io.yupiik.asciidoc.model.DescriptionList;
import io.yupiik.asciidoc.model.Document;
import io.yupiik.asciidoc.model.Element;
import io.yupiik.asciidoc.model.FloatingTitle;
import io.yupiik.asciidoc.model.Header;
import io.yupiik.asciidoc.model.HorizontalRule;
import io.yupiik.asciidoc.model.LineBreak;
import io.yupiik.asciidoc.model.Link;
import io.yupiik.asciidoc.model.Listing;
import io.yupiik.asciidoc.model.Macro;
import io.yupiik.asciidoc.model.OpenBlock;
import io.yupiik.asciidoc.model.OrderedList;
import io.yupiik.asciidoc.model.PageBreak;
import io.yupiik.asciidoc.model.Paragraph;
import io.yupiik.asciidoc.model.PassthroughBlock;
import io.yupiik.asciidoc.model.Quote;
import io.yupiik.asciidoc.model.Section;
import io.yupiik.asciidoc.model.Table;
import io.yupiik.asciidoc.model.Text;
import io.yupiik.asciidoc.model.UnOrderedList;
import io.yupiik.asciidoc.renderer.Visitor;

/**
 * Writes a parsed AsciiDoc document (the Yupiik {@code asciidoc-java} model) as GitHub-Flavored Markdown.
 * <p>
 * The renderer is the Markdown counterpart of Yupiik's {@code AsciidoctorLikeHtmlRenderer}: every block element appends
 * its Markdown followed by a blank line, nested content (admonitions, quotes, list items, table cells) is rendered by a
 * child renderer that shares the document state, and attribute references that cannot be resolved stay literal, so Qute
 * expressions in the source survive untouched. Nothing here ever throws on an unknown construct: it falls back to the
 * element's text.
 * <p>
 * Generated by Claude Code.
 */
public class MarkdownRenderer implements Visitor<String> {

    private static final Set<String> ADMONITION_STYLES = Set.of("NOTE", "TIP", "IMPORTANT", "CAUTION", "WARNING");
    private static final Pattern ATTRIBUTE_REFERENCE = Pattern.compile("\\{([a-zA-Z0-9_][a-zA-Z0-9_-]*)}");
    // a marker follows whitespace or a comment prefix, `a (1)` or `a //(1)`, while code reads `.statusCode(200)`
    private static final Pattern TRAILING_CALLOUTS = Pattern.compile("(?:\\s|//|#|--|;;)((?:\\s*\\(\\d+\\))+)\\s*$");
    private static final Pattern CALLOUT = Pattern.compile("\\((\\d+)\\)");
    private static final Pattern URL_SCHEME = Pattern.compile("^[a-zA-Z][a-zA-Z0-9+.-]*:");

    /** State shared by the root renderer and the child renderers it creates for nested blocks. */
    private static final class Shared {
        private final Map<String, String> siteAttributes;
        private final String fallbackTitle;
        private final List<String> footnotes = new ArrayList<>();
        private Map<String, String> documentAttributes = Map.of();
        private Map<String, String> sectionTitlesById = Map.of();

        private Shared(Map<String, String> siteAttributes, String fallbackTitle) {
            this.siteAttributes = siteAttributes;
            this.fallbackTitle = fallbackTitle;
        }
    }

    private final Shared shared;
    private final StringBuilder out = new StringBuilder();

    /**
     * @param siteAttributes attributes resolved when the document does not define them (site URL, page URL, ...)
     * @param fallbackTitle title used when the document has no title line (pages authored with YAML front matter)
     */
    public MarkdownRenderer(Map<String, String> siteAttributes, String fallbackTitle) {
        this.shared = new Shared(siteAttributes == null ? Map.of() : siteAttributes, fallbackTitle);
    }

    private MarkdownRenderer(Shared shared) {
        this.shared = shared;
    }

    // ------------------------------------------------------------------------------------------------------ document

    @Override
    public void visit(Document document) {
        final Header header = document.header();
        shared.documentAttributes = header == null || header.attributes() == null ? Map.of() : header.attributes();
        shared.sectionTitlesById = indexSectionTitles(document.body().children());
        String title = header == null ? null : header.title();
        if (title == null || title.isBlank()) {
            title = shared.fallbackTitle;
        }
        if (title != null && !title.isBlank()) {
            out.append("# ").append(substitute(title).strip()).append("\n\n");
        }
        visitBody(document.body());
    }

    @Override
    public void visitBody(Body body) {
        for (Element element : body.children()) {
            visitElement(element);
        }
    }

    @Override
    public ConditionalBlock.Context context() {
        return key -> {
            final String value = shared.documentAttributes.get(key);
            return value != null ? value : shared.siteAttributes.get(key);
        };
    }

    @Override
    public String result() {
        final StringBuilder result = new StringBuilder(out.toString().strip());
        if (!shared.footnotes.isEmpty()) {
            result.append("\n\n");
            for (int i = 0; i < shared.footnotes.size(); i++) {
                result.append("[^").append(i + 1).append("]: ").append(shared.footnotes.get(i).strip()).append('\n');
            }
        }
        return result.toString().strip() + "\n";
    }

    // -------------------------------------------------------------------------------------------------------- blocks

    @Override
    public void visitSection(Section section) {
        heading(section.level(), section.title(), section.options());
        for (Element child : section.children()) {
            visitElement(child);
        }
    }

    @Override
    public void visitFloatingTitle(FloatingTitle title) {
        heading(title.level(), title.title(), title.options());
    }

    private void heading(int level, Element title, Map<String, String> options) {
        anchor(options);
        out.append("#".repeat(Math.max(1, Math.min(level, 6)))).append(' ').append(inline(title).strip()).append("\n\n");
    }

    private void anchor(Map<String, String> options) {
        final String id = options == null ? null : options.get("id");
        if (id != null && !id.isBlank()) {
            out.append("<a id=\"").append(id.strip()).append("\"></a>\n");
        }
    }

    @Override
    public void visitParagraph(Paragraph paragraph) {
        anchor(paragraph.options());
        final StringBuilder run = new StringBuilder();
        for (Element child : paragraph.children()) {
            if (isInline(child)) {
                run.append(inline(child));
            } else {
                flush(run);
                visitElement(child);
            }
        }
        flush(run);
    }

    private void flush(StringBuilder run) {
        final String text = run.toString().strip();
        if (!text.isEmpty()) {
            out.append(text).append("\n\n");
        }
        run.setLength(0);
    }

    @Override
    public void visitText(Text text) {
        final String value = inline(text).strip();
        if ("'''".equals(value)) {
            // AsciiDoc's thematic break; the parser only recognizes --- and *** as rules.
            out.append("---\n\n");
            return;
        }
        if (!value.isEmpty()) {
            out.append(value).append("\n\n");
        }
    }

    @Override
    public void visitLink(Link link) {
        out.append(inline(link)).append("\n\n");
    }

    @Override
    public void visitAnchor(Anchor anchor) {
        out.append(inline(anchor)).append("\n\n");
    }

    @Override
    public void visitLineBreak(LineBreak lineBreak) {
        out.append('\n');
    }

    @Override
    public void visitAttribute(Attribute attribute) {
        final String value = context().attribute(attribute.attribute());
        if (value == null) {
            // Unresolved references stay literal; this is also what keeps Qute expressions such as {page.title} intact.
            out.append('{').append(attribute.attribute()).append("}\n\n");
            return;
        }
        for (Element element : attribute.evaluator().apply(value)) {
            visitElement(element);
        }
    }

    @Override
    public void visitCode(Code code) {
        if (code.inline()) {
            out.append(inline(code));
            return;
        }
        blockTitle(code.options());
        String value = code.value() == null ? "" : code.value();
        if (!code.callOuts().isEmpty()) {
            value = restoreCalloutMarkers(value,
                    code.callOuts().stream().map(CallOut::number).collect(Collectors.toSet()));
        }
        fence(language(code.options()), value);
        if (!code.callOuts().isEmpty()) {
            for (CallOut callOut : code.callOuts()) {
                out.append(callOut.number()).append(". ").append(inline(callOut.text()).strip()).append('\n');
            }
            out.append('\n');
        }
    }

    @Override
    public void visitListing(Listing listing) {
        final Map<String, String> options = options(listing.options());
        blockTitle(options);
        final String style = options.get("");
        final boolean diagramOrLanguage = style != null && !style.isBlank() && !"listing".equals(style)
                && !"literal".equals(style) && !"source".equals(style);
        fence(diagramOrLanguage ? style.strip() : language(options), listing.value() == null ? "" : listing.value());
    }

    private void fence(String language, String value) {
        final String fence = value.contains("```") ? "````" : "```";
        out.append(fence).append(language == null ? "" : language).append('\n').append(value);
        if (!value.endsWith("\n")) {
            out.append('\n');
        }
        out.append(fence).append("\n\n");
    }

    private static String language(Map<String, String> options) {
        if (options == null) {
            return "";
        }
        final String language = options.getOrDefault("language", options.get("lang"));
        return language == null ? "" : language.strip();
    }

    private void blockTitle(Map<String, String> options) {
        final String title = options == null ? null : options.get("title");
        if (title != null && !title.isBlank()) {
            out.append("**").append(substitute(title).strip()).append("**\n\n");
        }
    }

    /**
     * The parser rewrites callout markers inside code from {@code <1>} to {@code (1)}; AsciiDoc readers (and downdoc)
     * expect the angle-bracket form, so put it back on trailing markers only. Code that ends in parentheses, such as
     * {@code .statusCode(200)} or {@code @Priority(1)}, is not a marker: a marker follows whitespace or a comment prefix
     * and carries the number of one of the block's callouts.
     *
     * @param value the code of the block
     * @param numbers the numbers of the block's callouts
     */
    static String restoreCalloutMarkers(String value, Set<Integer> numbers) {
        final String[] lines = value.split("\n", -1);
        for (int i = 0; i < lines.length; i++) {
            final Matcher matcher = TRAILING_CALLOUTS.matcher(lines[i]);
            if (matcher.find() && CALLOUT.matcher(matcher.group(1)).results()
                    .allMatch(marker -> numbers.contains(Integer.parseInt(marker.group(1))))) {
                lines[i] = lines[i].substring(0, matcher.start(1)) + CALLOUT.matcher(matcher.group(1)).replaceAll("<$1>");
            }
        }
        return String.join("\n", lines);
    }

    @Override
    public void visitUnOrderedList(UnOrderedList list) {
        renderList(list.children(), false, options(list.options()));
    }

    @Override
    public void visitOrderedList(OrderedList list) {
        renderList(list.children(), true, options(list.options()));
    }

    private void renderList(List<Element> items, boolean ordered, Map<String, String> options) {
        blockTitle(options);
        int number = 1;
        if (ordered && options.get("start") != null) {
            try {
                number = Integer.parseInt(options.get("start").strip());
            } catch (NumberFormatException ignored) {
                // keep the default
            }
        }
        for (Element item : items) {
            final String marker = ordered ? number++ + ". " : "- ";
            final StringBuilder text = new StringBuilder();
            final List<Element> blocks = new ArrayList<>();
            splitListItem(item, text, blocks);
            out.append(marker).append(checkbox(item)).append(text.toString().strip()).append('\n');
            final String indent = " ".repeat(marker.length());
            for (Element block : blocks) {
                final String rendered = block(List.of(block));
                if (rendered.isEmpty()) {
                    continue;
                }
                final boolean nestedList = block.type() == Element.ElementType.UNORDERED_LIST
                        || block.type() == Element.ElementType.ORDERED_LIST;
                if (!nestedList) {
                    out.append('\n');
                }
                out.append(indent(rendered, indent)).append('\n');
                if (!nestedList) {
                    out.append('\n');
                }
            }
        }
        out.append('\n');
    }

    private static String checkbox(Element item) {
        if (item instanceof Paragraph paragraph && paragraph.options() != null
                && paragraph.options().containsKey("checkbox")) {
            final boolean checked = paragraph.options().containsKey("checked")
                    && !"false".equalsIgnoreCase(paragraph.options().get("checked"));
            return checked ? "[x] " : "[ ] ";
        }
        return "";
    }

    /** A list item is a run of inline elements followed by nested blocks (the parser attaches a nested list there). */
    private void splitListItem(Element item, StringBuilder text, List<Element> blocks) {
        if (item instanceof Paragraph paragraph) {
            for (Element child : paragraph.children()) {
                if (isInline(child)) {
                    text.append(inline(child));
                } else {
                    blocks.add(child);
                }
            }
        } else if (isInline(item)) {
            text.append(inline(item));
        } else {
            blocks.add(item);
        }
    }

    @Override
    public void visitDescriptionList(DescriptionList list) {
        // The parser hands the document attributes over as this list's options, so there is no block title to print.
        for (Map.Entry<Element, Element> entry : list.children().entrySet()) {
            out.append("**").append(inline(entry.getKey()).strip()).append("**");
            final Element description = entry.getValue();
            if (description == null) {
                out.append("\n\n");
            } else if (isInline(description) || description instanceof Paragraph paragraph
                    && paragraph.children().stream().allMatch(MarkdownRenderer::isInline)) {
                out.append("\\\n").append(inline(description).strip()).append("\n\n");
            } else {
                out.append("\n\n").append(indent(block(List.of(description)), "  ")).append("\n\n");
            }
        }
    }

    @Override
    public void visitAdmonition(Admonition admonition) {
        alert(admonition.level().name(), options(admonition.options()), List.of(admonition.content()));
    }

    private void alert(String level, Map<String, String> options, List<Element> content) {
        out.append("> [!").append(level).append("]\n");
        final String title = options.get("title");
        if (title != null && !title.isBlank()) {
            out.append("> **").append(substitute(title).strip()).append("**\n>\n");
        }
        out.append(quote(block(content))).append("\n\n");
    }

    @Override
    public void visitOpenBlock(OpenBlock block) {
        final Map<String, String> options = options(block.options());
        final String style = options.get("");
        if (style != null && ADMONITION_STYLES.contains(style.strip().toUpperCase(Locale.ROOT))) {
            alert(style.strip().toUpperCase(Locale.ROOT), options, block.children());
            return;
        }
        if (options.containsKey("collapsible-option")) {
            final String title = options.getOrDefault("title", "Details");
            out.append("<details>\n<summary>").append(substitute(title).strip()).append("</summary>\n\n")
                    .append(block(block.children())).append("\n\n</details>\n\n");
            return;
        }
        blockTitle(options);
        final String body = block(block.children());
        if (!body.isEmpty()) {
            out.append(body).append("\n\n");
        }
    }

    @Override
    public void visitQuote(Quote quoteBlock) {
        final Map<String, String> options = options(quoteBlock.options());
        blockTitle(options);
        final StringBuilder body = new StringBuilder(block(quoteBlock.children()));
        final String attribution = options.get("attribution");
        final String cite = options.get("citetitle");
        if (attribution != null && !attribution.isBlank()) {
            body.append("\n\n\u2014 ").append(attribution.strip());
            if (cite != null && !cite.isBlank()) {
                body.append(", ").append(cite.strip());
            }
        } else if (cite != null && !cite.isBlank()) {
            body.append("\n\n\u2014 ").append(cite.strip());
        }
        out.append(quote(body.toString())).append("\n\n");
    }

    @Override
    public void visitTable(Table table) {
        final List<List<Element>> rows = table.elements();
        if (rows == null || rows.isEmpty()) {
            return;
        }
        final Map<String, String> options = options(table.options());
        blockTitle(options);
        final int columns = rows.stream().mapToInt(List::size).max().orElse(0);
        if (columns == 0) {
            return;
        }
        final boolean header = !options.containsKey("noheader-option");
        final List<String> headerCells = new ArrayList<>();
        int first = 0;
        if (header) {
            for (Element cell : rows.get(0)) {
                headerCells.add(cell(cell));
            }
            first = 1;
        }
        while (headerCells.size() < columns) {
            headerCells.add("");
        }
        out.append("| ").append(String.join(" | ", headerCells)).append(" |\n");
        out.append("|").append(" --- |".repeat(columns)).append('\n');
        for (int i = first; i < rows.size(); i++) {
            final List<String> cells = new ArrayList<>();
            for (Element cell : rows.get(i)) {
                cells.add(cell(cell));
            }
            while (cells.size() < columns) {
                cells.add("");
            }
            out.append("| ").append(String.join(" | ", cells)).append(" |\n");
        }
        out.append('\n');
    }

    /** Cells are single-line in GFM: block content is flattened and pipes are escaped. */
    private String cell(Element element) {
        final String text = isInline(element) || element instanceof Paragraph ? inline(element) : block(List.of(element));
        return text.strip().replace("|", "\\|").replace("\n\n", "<br><br>").replace("\n", "<br>");
    }

    @Override
    public void visitPassthroughBlock(PassthroughBlock block) {
        if (block.value() != null && !block.value().isBlank()) {
            out.append(block.value().strip()).append("\n\n");
        }
    }

    @Override
    public void visitHorizontalRule(HorizontalRule rule) {
        out.append("---\n\n");
    }

    @Override
    public void visitPageBreak(PageBreak pageBreak) {
        // Markdown has no page break.
    }

    @Override
    public void visitConditionalBlock(ConditionalBlock block) {
        final ConditionalBlock.Context context = context();
        if (block.evaluator().test(context)) {
            for (Element element : block.children()) {
                visitElement(element);
            }
            return;
        }
        if (block.elseBranches() == null) {
            return;
        }
        for (ConditionalBlock branch : block.elseBranches()) {
            if (branch.evaluator().test(context)) {
                for (Element element : branch.children()) {
                    visitElement(element);
                }
                return;
            }
        }
    }

    @Override
    public void visitMacro(Macro macro) {
        if (macro.inline()) {
            out.append(inline(macro));
            return;
        }
        final Map<String, String> options = options(macro.options());
        switch (macro.name()) {
            case "image" -> {
                out.append(image(macro));
                final String title = options.get("title");
                if (title != null && !title.isBlank()) {
                    out.append("\n*").append(substitute(title).strip()).append('*');
                }
                out.append("\n\n");
            }
            case "toc", "include" -> {
                // nothing to show
            }
            case "video", "audio" -> {
                final String target = substitute(macro.label() == null ? "" : macro.label()).strip();
                out.append('[').append(target).append("](").append(target).append(")\n\n");
            }
            default -> {
                final String text = inlineMacro(macro).strip();
                if (!text.isEmpty()) {
                    out.append(text).append("\n\n");
                }
            }
        }
    }

    // -------------------------------------------------------------------------------------------------------- inline

    private static boolean isInline(Element element) {
        return switch (element.type()) {
            case TEXT, LINK, ANCHOR, ATTRIBUTE, LINE_BREAK -> true;
            case CODE -> ((Code) element).inline();
            case MACRO -> ((Macro) element).inline();
            default -> false;
        };
    }

    /** Renders one element as inline Markdown; block elements are rendered by a child renderer and returned as text. */
    String inline(Element element) {
        if (element == null) {
            return "";
        }
        return switch (element.type()) {
            case TEXT -> text((Text) element);
            case CODE -> {
                final Code code = (Code) element;
                yield code.inline() ? inlineCode(code.value()) : block(List.of(element));
            }
            case LINK -> link((Link) element);
            case MACRO -> {
                final Macro macro = (Macro) element;
                yield macro.inline() ? inlineMacro(macro) : block(List.of(element));
            }
            case ANCHOR -> anchorLink((Anchor) element);
            case ATTRIBUTE -> attributeText((Attribute) element);
            case LINE_BREAK -> "\\\n";
            case PARAGRAPH -> inlineChildren(((Paragraph) element).children());
            default -> block(List.of(element));
        };
    }

    private String inlineChildren(List<Element> children) {
        final StringBuilder text = new StringBuilder();
        for (Element child : children) {
            text.append(inline(child));
        }
        return text.toString();
    }

    private String text(Text text) {
        final String value = text.value() == null ? "" : text.value();
        final Map<String, String> options = options(text.options());
        final String id = options.get("id");
        final String prefix = id != null && !id.isBlank() ? "<a id=\"" + id.strip() + "\"></a>" : "";
        if (text.style() == null || text.style().isEmpty() || value.isBlank()) {
            return prefix + value;
        }
        // GFM emphasis cannot start or end with a space: keep surrounding whitespace outside the markup.
        int start = 0;
        while (start < value.length() && Character.isWhitespace(value.charAt(start))) {
            start++;
        }
        int end = value.length();
        while (end > start && Character.isWhitespace(value.charAt(end - 1))) {
            end--;
        }
        String styled = value.substring(start, end);
        for (Text.Style style : text.style()) {
            styled = switch (style) {
                case BOLD -> "**" + styled + "**";
                case ITALIC, EMPHASIS -> "*" + styled + "*";
                case STRIKETHROUGH -> "~~" + styled + "~~";
                case MARK -> "<mark>" + styled + "</mark>";
                case SUB -> "<sub>" + styled + "</sub>";
                case SUP -> "<sup>" + styled + "</sup>";
                default -> styled;
            };
        }
        return prefix + value.substring(0, start) + styled + value.substring(end);
    }

    private static String inlineCode(String value) {
        final String code = value == null ? "" : value;
        return code.contains("`") ? "`` " + code + " ``" : "`" + code + "`";
    }

    private String link(Link link) {
        final String url = substitute(link.url() == null ? "" : link.url()).strip();
        final String label = link.label() == null ? "" : inline(link.label()).strip();
        if (label.isEmpty() || label.equals(url)) {
            // The parser keeps punctuation that follows a bare URL as part of it; move it back after the link.
            int end = url.length();
            while (end > 0 && ".,;:!?".indexOf(url.charAt(end - 1)) >= 0) {
                end--;
            }
            return "<" + url.substring(0, end) + ">" + url.substring(end);
        }
        return "[" + label + "](" + url + ")";
    }

    private String anchorLink(Anchor anchor) {
        final String id = anchor.value() == null ? "" : anchor.value().strip();
        String label = anchor.label();
        if (label == null || label.isBlank()) {
            label = shared.sectionTitlesById.getOrDefault(id, id);
        }
        return "[" + label.strip() + "](#" + id + ")";
    }

    private String attributeText(Attribute attribute) {
        final String value = context().attribute(attribute.attribute());
        if (value == null) {
            return "{" + attribute.attribute() + "}";
        }
        return inlineChildren(attribute.evaluator().apply(value));
    }

    private String inlineMacro(Macro macro) {
        final Map<String, String> options = options(macro.options());
        final String label = macro.label() == null ? "" : macro.label();
        // Bracket-only macros such as kbd:[Ctrl+C] carry their content in the positional option, not in the label.
        final String content = label.isBlank() ? options.getOrDefault("", "") : label;
        return switch (macro.name()) {
            case "image" -> image(macro);
            case "link" -> "[" + substitute(options.getOrDefault("", label)).strip() + "](" + substitute(label).strip() + ")";
            case "xref" -> xref(macro, options);
            case "mailto" -> "[" + options.getOrDefault("", label).strip() + "](mailto:" + label.strip() + ")";
            case "kbd" -> keys(content);
            case "btn" -> "**" + content.strip() + "**";
            case "menu" -> "**" + label.strip() + (options.get("") != null ? " > " + options.get("").strip() : "") + "**";
            case "pass" -> content;
            case "icon", "toc", "include" -> "";
            case "footnote" -> footnote(options.getOrDefault("", label));
            case "stem", "latexmath", "asciimath" -> "$" + content.strip() + "$";
            default -> options.getOrDefault("", label);
        };
    }

    private static String keys(String label) {
        final List<String> keys = new ArrayList<>();
        for (String key : label.split("\\+")) {
            if (!key.isBlank()) {
                keys.add("<kbd>" + key.strip() + "</kbd>");
            }
        }
        return String.join("+", keys);
    }

    private String footnote(String text) {
        shared.footnotes.add(text);
        return "[^" + shared.footnotes.size() + "]";
    }

    /**
     * {@code xref:page.adoc#id[text]} points at the other page's twin: twins live at {@code <page-url>index.md}, so the
     * sibling page {@code page.adoc} is {@code ../page/index.md} from this twin (see {@link #twinOf(String)}); same-page
     * references keep {@code #id}.
     */
    private String xref(Macro macro, Map<String, String> options) {
        final String target = substitute(macro.label() == null ? "" : macro.label()).strip();
        final int hash = target.indexOf('#');
        final String file = hash >= 0 ? target.substring(0, hash) : target;
        final String fragment = hash >= 0 ? target.substring(hash + 1) : "";
        final String path = file.endsWith(".adoc") ? twinOf(file) : file;
        final String href = file.isEmpty() ? "#" + fragment : fragment.isEmpty() ? path : path + "#" + fragment;
        String text = options.get("");
        if (text == null || text.isBlank()) {
            if (file.isEmpty()) {
                text = shared.sectionTitlesById.getOrDefault(fragment, fragment);
            } else {
                text = fragment.isEmpty() ? path : fragment;
            }
        }
        return "[" + text.strip() + "](" + href + ")";
    }

    /**
     * The twin of another AsciiDoc page, as a link from this page's twin. Both twins sit at {@code <page-url>index.md},
     * so a sibling {@code page.adoc} becomes {@code ../page/index.md} and a site-absolute {@code /docs/page.adoc} becomes
     * {@code /docs/page/index.md}.
     */
    static String twinOf(String adocPath) {
        String page = adocPath.substring(0, adocPath.length() - ".adoc".length());
        if (page.startsWith("./")) {
            page = page.substring(2);
        }
        return (page.startsWith("/") ? page : "../" + page) + "/index.md";
    }

    private String image(Macro macro) {
        final Map<String, String> options = options(macro.options());
        String target = substitute(macro.label() == null ? "" : macro.label()).strip();
        if (!target.isEmpty() && !target.startsWith("/") && !URL_SCHEME.matcher(target).find()) {
            final String imagesDir = context().attribute("imagesdir");
            if (imagesDir != null && !imagesDir.isBlank()) {
                final String dir = substitute(imagesDir).strip();
                target = dir.endsWith("/") ? dir + target : dir + "/" + target;
            }
        }
        String alt = options.get("alt");
        if (alt == null || alt.isBlank()) {
            alt = options.get("");
        }
        if (alt == null || alt.isBlank()) {
            final String name = target.substring(target.lastIndexOf('/') + 1);
            final int dot = name.lastIndexOf('.');
            alt = dot > 0 ? name.substring(0, dot) : name;
        }
        final String image = "![" + alt.strip() + "](" + target + ")";
        final String link = options.get("link");
        return link != null && !link.isBlank() ? "[" + image + "](" + substitute(link).strip() + ")" : image;
    }

    // ------------------------------------------------------------------------------------------------------- helpers

    /** Renders elements with a child renderer sharing this document's state; the result has no trailing blank line. */
    private String block(List<Element> elements) {
        final MarkdownRenderer child = new MarkdownRenderer(shared);
        for (Element element : elements) {
            child.visitElement(element);
        }
        return child.out.toString().strip();
    }

    private static String quote(String text) {
        return text.lines().map(line -> line.isEmpty() ? ">" : "> " + line).collect(Collectors.joining("\n"));
    }

    private static String indent(String text, String indent) {
        return text.lines().map(line -> line.isEmpty() ? line : indent + line).collect(Collectors.joining("\n"));
    }

    private static Map<String, String> options(Map<String, String> options) {
        return options == null ? Map.of() : options;
    }

    /** Replaces {@code {name}} references the document or the site defines; unknown references stay literal. */
    private String substitute(String text) {
        if (text == null || text.indexOf('{') < 0) {
            return text;
        }
        final Matcher matcher = ATTRIBUTE_REFERENCE.matcher(text);
        final StringBuilder result = new StringBuilder();
        while (matcher.find()) {
            final String value = context().attribute(matcher.group(1));
            matcher.appendReplacement(result, Matcher.quoteReplacement(value == null ? matcher.group() : value));
        }
        matcher.appendTail(result);
        return result.toString();
    }

    private Map<String, String> indexSectionTitles(List<Element> elements) {
        final Map<String, String> titles = new HashMap<>();
        collectTitles(elements, titles);
        return titles;
    }

    private void collectTitles(List<Element> elements, Map<String, String> titles) {
        for (Element element : elements) {
            if (element instanceof Section section) {
                registerTitle(section.options(), section.title(), titles);
                collectTitles(section.children(), titles);
            } else if (element instanceof FloatingTitle floatingTitle) {
                registerTitle(floatingTitle.options(), floatingTitle.title(), titles);
            } else if (element instanceof ConditionalBlock conditional) {
                collectTitles(conditional.children(), titles);
                if (conditional.elseBranches() != null) {
                    for (ConditionalBlock branch : conditional.elseBranches()) {
                        collectTitles(branch.children(), titles);
                    }
                }
            } else if (element instanceof OpenBlock openBlock) {
                collectTitles(openBlock.children(), titles);
            }
        }
    }

    private void registerTitle(Map<String, String> options, Element title, Map<String, String> titles) {
        final String id = options == null ? null : options.get("id");
        if (id != null && !id.isBlank()) {
            titles.put(id.strip(), inline(title).strip());
        }
    }
}
