package io.quarkiverse.roq.plugin.markdowntwin.deployment;

import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Decides which pages get a twin, from the configured include and exclude patterns.
 * <p>
 * Patterns are matched against the page path relative to the site root, without a leading slash, which is the shape
 * Roq uses for {@code RoqUrl#resourcePath()}. A leading slash is accepted on both sides so that the patterns can be
 * written the way they appear in a URL and reused verbatim in a CDN rule.
 * <p>
 * Generated by Claude Code.
 */
final class TwinScope {

    private static final String GLOB_PREFIX = "glob:";
    private static final String REGEX_PREFIX = "regex:";

    private final List<PathMatcher> include;
    private final List<PathMatcher> exclude;

    private TwinScope(List<PathMatcher> include, List<PathMatcher> exclude) {
        this.include = include;
        this.exclude = exclude;
    }

    static TwinScope of(MarkdownTwinConfig config) {
        return new TwinScope(compile(config.include()), compile(config.exclude()));
    }

    /**
     * Whether the page at this resource path is in scope: it matches an include pattern, or there are none, and it
     * matches no exclude pattern.
     */
    boolean includes(String resourcePath) {
        if (resourcePath == null) {
            return false;
        }
        final Path path = Path.of(normalizePath(resourcePath));
        if (!include.isEmpty() && include.stream().noneMatch(m -> m.matches(path))) {
            return false;
        }
        return exclude.stream().noneMatch(m -> m.matches(path));
    }

    private static List<PathMatcher> compile(Optional<List<String>> patterns) {
        final List<PathMatcher> matchers = new ArrayList<>();
        for (String pattern : patterns.orElse(List.of())) {
            if (pattern == null || pattern.isBlank()) {
                continue;
            }
            matchers.add(Path.of("").getFileSystem().getPathMatcher(normalizePattern(pattern.strip())));
        }
        return List.copyOf(matchers);
    }

    /**
     * A bare pattern is a glob, matching {@code site.ignored-files}. A leading slash is dropped from a glob so that
     * {@code /guides/**} and {@code guides/**} behave the same; an explicit regex is left untouched, since a slash
     * there may be deliberate.
     */
    private static String normalizePattern(String pattern) {
        if (pattern.startsWith(REGEX_PREFIX)) {
            return pattern;
        }
        final String glob = pattern.startsWith(GLOB_PREFIX) ? pattern.substring(GLOB_PREFIX.length()) : pattern;
        return GLOB_PREFIX + stripLeadingSlash(glob);
    }

    private static String normalizePath(String resourcePath) {
        return stripLeadingSlash(resourcePath);
    }

    private static String stripLeadingSlash(String value) {
        return value.startsWith("/") ? value.substring(1) : value;
    }
}
