package io.quarkiverse.roq.plugin.markdowntwin.deployment;

import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Predicate;
import java.util.regex.Pattern;

/**
 * Decides which pages get a twin, from the configured include and exclude patterns.
 * <p>
 * Patterns are matched against the page path relative to the site root, without a leading slash, which is the shape
 * Roq uses for {@code RoqUrl#resourcePath()}. A leading slash is accepted on both sides so that the patterns can be
 * written the way they appear in a URL and reused verbatim in a CDN rule.
 * <p>
 * Generated by Claude Code.
 */
final class TwinScope {

    private static final String GLOB_PREFIX = "glob:";
    private static final String REGEX_PREFIX = "regex:";

    private final List<Predicate<String>> include;
    private final List<Predicate<String>> exclude;

    private TwinScope(List<Predicate<String>> include, List<Predicate<String>> exclude) {
        this.include = include;
        this.exclude = exclude;
    }

    static TwinScope of(MarkdownTwinConfig config) {
        return new TwinScope(compile(config.include()), compile(config.exclude()));
    }

    /**
     * Whether the page at this resource path is in scope: it matches an include pattern, or there are none, and it
     * matches no exclude pattern.
     */
    boolean includes(String resourcePath) {
        if (resourcePath == null) {
            return false;
        }
        final String path = normalizePath(resourcePath);
        if (!include.isEmpty() && include.stream().noneMatch(m -> m.test(path))) {
            return false;
        }
        return exclude.stream().noneMatch(m -> m.test(path));
    }

    private static List<Predicate<String>> compile(Optional<List<String>> patterns) {
        final List<Predicate<String>> matchers = new ArrayList<>();
        for (String pattern : patterns.orElse(List.of())) {
            if (pattern == null || pattern.isBlank()) {
                continue;
            }
            matchers.add(matcher(pattern.strip()));
        }
        return List.copyOf(matchers);
    }

    /**
     * A bare pattern is a glob, matching {@code site.ignored-files}. A leading slash is dropped on both sides so that
     * {@code /guides/**} and {@code guides/**} behave the same.
     * <p>
     * A glob is compiled by the default file system, the way Roq compiles {@code site.ignored-files}. A regex is
     * matched against the path string directly instead: a {@link PathMatcher} matches a regex against
     * {@link Path#toString()}, which is backslash-separated on Windows, so a regex written with slashes would match
     * nothing there.
     */
    private static Predicate<String> matcher(String pattern) {
        if (pattern.startsWith(REGEX_PREFIX)) {
            return Pattern.compile(stripLeadingSlash(pattern.substring(REGEX_PREFIX.length()))).asMatchPredicate();
        }
        final String glob = pattern.startsWith(GLOB_PREFIX) ? pattern.substring(GLOB_PREFIX.length()) : pattern;
        final PathMatcher matcher = Path.of("").getFileSystem().getPathMatcher(GLOB_PREFIX + stripLeadingSlash(glob));
        return path -> matcher.matches(Path.of(path));
    }

    private static String normalizePath(String resourcePath) {
        return stripLeadingSlash(resourcePath);
    }

    private static String stripLeadingSlash(String value) {
        return value.startsWith("/") ? value.substring(1) : value;
    }
}
